imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.annonce_images: /uploads/images/annonces

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

vich_uploader:
    db_driver: orm
    mappings:
        annonce_images:
            uri_prefix:         '%app.path.annonce_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/annonces'
            namer: vich_uploader.namer_uniqid

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Admin
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

easy_admin:
    site_name: 'Carcassonne Immo'
    design:
        menu:
        - { label: 'Accueil du site', url: 'http://127.0.0.1:8000' }
        - User
        - Annonce
        - Client
        - TypeAnnonce
        form_theme: vertical
    show:
        max_results: 20
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'times', label: ''}
            - { name: 'new', label: 'Créer'}
    entities:
        User:
            class: AppBundle\Entity\Admin
            label: 'Employés'
            list:
                title: 'Liste des employés'
                fields:
                    - id
                    - prenom
                    - nom
                    - { property: 'tel',  label: 'Téléphone' }
                    - { property: 'username', label: 'Pseudo' }
                    - email
                    - { property: 'enabled', label: 'Compte activé' }
            form:
                title: 'Créer/Modifier un employé'
                fields:
                    - { type: 'group' }
                    - prenom
                    - nom
                    - email
                    - { property: 'tel', label: 'Téléphone' }
                    - { type: 'group' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'password', type_options: { required: false } }
            show:
                title: 'Employé %%entity_id%%'
                fields:
                    - prenom
                    - nom
                    - email
                    - { property: 'tel', label: 'Téléphone' }
                    - { property: 'username', label: 'Pseudo' }
        Annonce:
            class: AppBundle\Entity\Annonce
            label: 'Annonces'
            list:
                title: 'Liste des annonces'
                fields:
                    - id
                    - { property: 'ann_photo', type: 'image', base_path: '%app.path.annonce_images%', label: "Photo de l'annonce"}
                    - { property: 'ann_titre', label: "Titre de l'annonce"}
                    - { property: 'ann_nbpieces', label: 'Nombre de pièces'}
                    - { property: 'ann_prix', label: 'Prix' }
                    - { property: 'client', label: 'Propriétaire' }
                    - { property: 'admin', label: 'Vendeur' }
                    - { property: 'typeAnn', label: "Type de l'annonce" }
            form:
                title: 'Créer/Modifier une annonce'
                fields:
                    - { type: 'group' }
                    - { property: 'ann_titre', type: 'text', label: "Titre de l'annonce", type_options: { required: true }}
                    - { property: 'ann_nbpieces', type: 'integer', label: 'Nombre de pièces', type_options: { required: true }}
                    - { property: 'ann_prix', type: 'integer', label: 'Prix', type_options: { required: true }}
                    - { property: 'imageFile', type: 'file', label: 'Photo', base_path: '%app.path.annonce_images%' }
                    - { property: 'ann_description', label: 'Description' }
                    - { property: 'client', label: 'Propriétaire', type_options: { required: true } }
                    - { property: 'admin', label: "Employé sur l'annonce", type_options: { required: true } }
                    - { property: 'typeAnn', label: "Type de l'annonce", type_options: { required: true }}
        Client:
            class: AppBundle\Entity\Client
            label: 'Clients'
            list:
                title: 'Liste des clients'
                fields:
                    - id
                    - prenom
                    - nom
                    - { property: 'tel', label: 'Téléphone' }
            form:
                title: 'Créer/Modifier un client'
                fields:
                    - prenom
                    - nom
                    - { property: 'tel', label: 'Téléphone' }
            show:
                title: 'Client %%entity_id%%'
                fields:
                    - prenom
                    - nom
                    - { property: 'tel', label: 'Téléphone' }
        TypeAnnonce:
            class: AppBundle\Entity\TypeAnnonce
            label: 'Type des annonces'
            show:
                title: 'Type Annonce %%entity_id%%'
                fields:
                    - type